### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by grammaton** [DavideCroci-music/STALPM1#1]
Davide, ho apportato qualche correzione alla struttura del file latex che dava errori di compilazione.
Per i contenuti, l'unica cosa che ti posso segnalare è che il filtro utilizzato è di tipo passa basso, ispirato al filtro Ladder di Moog. Ne consegue che la tua descrizione del filtro è da rifare e anche quella del Q.

g

**Comment by DavideCroci-music** [comment]
Perfetto grazie. Appena torno a casa correggo sistemo il pdf e mando.
Grazie di nuovo.

Saluti,

Davide Croci

Il dom 12 lug 2020, 09:24 Giuseppe Silvi <notifications@github.com> ha
scritto:

**Comment by DavideCroci-music** [comment]
Prof. Silvi buonasera e scusi. Ho caricato la nuova versione più o meno definitiva e corretta del fil e tex, ma non riesco a convertire in pdf…mi manca qualche passaggio, non mi produce proprio il file pdf.
Scusi e grazie

Saluti, Davide Croci

**Comment by grammaton** [comment]
ciao davide,
non so perché ma avevi di nuovo tolto tutti gli environment di codice attorno al codice di faust. l'ho rimesso.
a me compila, per sicurezza ti metto il pdf nelle release

https://github.com/DavideCroci-music/STALPM1/releases/tag/1
